# These are supported funding model platforms

#liberapay: kevinperdana1989
#issuehunt: kevinperdana1989
custom: ['https://paypal.me/sonyarianto'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
